---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-nfs
  namespace: media
spec:
  resources:
    requests:
      storage: 50Ti
  volumeMode: Filesystem
  storageClassName: nfs-manual
  accessModes:
    - ReadWriteMany
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-nfs
spec:
  capacity:
    storage: 50Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: "media"
    name: "media-nfs"
  mountOptions:
    - nfsvers=3
    - nolock
    - noatime
  storageClassName: nfs-manual
  csi:
    driver: org.democratic-csi.nfs-manual
    readOnly: false
    fsType: nfs
    volumeHandle: media-nfs  # make sure it's a unique id in the cluster
    volumeAttributes:
      server: 192.168.100.148
      share: /mnt/data/data
      node_attach_driver: nfs
      provisioner_driver: node-manual
