ansible_become_pass: ENC[AES256_GCM,data:1bBzvd1JXBlxOcZm7g==,iv:dW/IPPhLv4i6+URs70FiFccAR+czyMRviwQuhQUOneU=,tag:4gfzomQGSPW4DWVFTsdKrA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x7pwg44zy2dcydntr0n7rcdtekua2fgm3gsy63amu55lhktsnd7qw40grw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqdHV4ZDllUCtZd1V5ZTBG
            WWh3THlIQ3hZTUcwZ2JIOWhBblJQNHBZZXpVCmoyeEZSRGhndENORGZ4WUJ4MnA2
            MW8xZUhmVVVaM0p0aFVINFVXYm9OWW8KLS0tIG9JeVFKZy9EaGw0dFZwYzFoWWVl
            dk8yU0dNYk9RS25yVE9ZM1hIQzhlSFkKcFU1LedhR8NEa+x8PA+/zWQh/QNdabVJ
            ooPUl9mZiaNQyGl/QsEd30m4euRrUNkAujgQF5gLK+F18cvGXDL0Yg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-25T19:13:52Z"
    mac: ENC[AES256_GCM,data:OnQCsKJSBSYbPnDDzOxi8suGZ3kXz63S9Mzb1lKgczxhspNhvUz1NyYfjIN1gaV9ls5uflk+OfSvdk3djDtZZYDzw/NjXuIIAgwGK5U/sPxo1ssqdNQE8L6ocBi4ACF81ZmM+y6/vemGXGULocOywoY12FmVMiE5FxvMX4nLckQ=,iv:N5PHUamMpgmeAT7My5e17vc/8fVrRR7PjbAXnH3usiI=,tag:dXmMHc/gR1Lm4Nmtss6GBw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
