ansible_become_pass: ENC[AES256_GCM,data:kKvHkwddIGt0mR5KUA==,iv:iXVi+iZFfmh8/jC0BuqqfYTT/H5PdPtAU1EjrP3CTuE=,tag:nm4UE0OsN7fDLiKfu48dSQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x7pwg44zy2dcydntr0n7rcdtekua2fgm3gsy63amu55lhktsnd7qw40grw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDWXpScXIzMDNtNHBuelN2
            a3h3N3ltWGNvc0U0UkNOTjNQN1NKNXBvZjNJClVMM2MvUFJVb0hXdkZ4RjBnNEZV
            bzdlL3JYSGFlMXV5eGlCSkpIU1B6Q1EKLS0tIEwrYlI3TmZubFpLR0Q2SU4xaUFC
            dlpFN2pBeDBGL1BNOEsrOXF1L1R2alUK5FwTebCiDprknSFxDt390hLxc/YQzkXo
            0NthNm89kGffVG/2GTpTPBCu4pcMChPnCZ07P3DCjoTgpT18okPZjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-31T02:56:29Z"
    mac: ENC[AES256_GCM,data:5D6eL0kw1TGDK8MGT3uG3Zxg+1AxR4SNRmXKtExV9OdfvvcKlRmTiCqWzZ2CRybz8n21omaeKMB5QNMl9j6PU4WGN0L24PuCFXkSIsG9HVe/Gcy+jWFElZialFmhNZ+MZ0DMM2H9y+aUQ3rztjUYMydT4exspm9l8Vo5Upd9q50=,iv:PvnVecDqsN5YhmCiLwLI6a/+JPb1P4+nxYgG1fQjK3c=,tag:V1kvHC5hB/44UTcwlvOK0w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
