ansible_become_pass: ENC[AES256_GCM,data:9DWl5iEWXk/+KkRdyQ==,iv:ULDxbKeJGNnErSRfAj3XRIpSl3PT4QRioyZUmyxc9Cw=,tag:GUaOgCXdhNXxjdLUc6qtyQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x7pwg44zy2dcydntr0n7rcdtekua2fgm3gsy63amu55lhktsnd7qw40grw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbTBVVTNDZTA2enVBMDIy
            K3UrdU5xUU1SUThwcmN2RmNURFpRMVdYRkFvCmx5bVFFaGtVTndwK2NXcU4rUGE0
            U2wrUUVNaHlhZnBGcnBBM093dFN3eDQKLS0tIGlGVldUYnp5cFhUbzJ3K0hGbC8z
            NXhvTzZ0UktuOERyNXhaSHVKb0I0RFEKvhT07FyfYNkM9nHbmY3CtMAPutOmqDf2
            Pr2JGV4uRLPGqOWbEpD3EfBNnnjnel9LC5bNaG0X03k5U8qwRdHEUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-25T19:13:51Z"
    mac: ENC[AES256_GCM,data:lm2btnLWrgK7+Ozj3gvBzj5OKOt5fbMmCUB9bBC5dCbieeid+0iOQnanIruSGfMFttlo8al1TmZ6kpaeVXWBFCXZebTPjSGdOGtuCNjX0y+R4ZlpSCVeda0E2WPTGbAwkJj+oVwIPdsXIFsJjNo4R/EhyQu/Bdy5irWBgtGvRKg=,iv:NL3ANe4t1NwomFjZ+u//8OHkYL4SW3T/6SOJOBEYuD0=,tag:iNUfAGOqnrdS/k6Md8JKew==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
