ansible_become_pass: ENC[AES256_GCM,data:drjVqqB/Ha65bQLgoA==,iv:WhCba+jNi+6LVQVzSddKJKBMDkJjUt8q5HiJJtBA9+E=,tag:/NdVPTGAKV2Y6g42Jhwz+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x7pwg44zy2dcydntr0n7rcdtekua2fgm3gsy63amu55lhktsnd7qw40grw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMHNRQXphU1U1UHZaOHYv
            TjdIWmdwajhYU1R2cG5kSHBISUlTZDJQdVJRCkZjSzR5OERvSEZKMStEUktoVXFD
            WndGcmhzQUNjdGVORURjQWlIdDJTak0KLS0tIEEveUsrdlFReFhkR21ibmNqclJ3
            akFqSERRWkZ4UldrR2NSWmg4WlhNWm8KZxN/OkPoNDLXvVWi2K/Qx0jOdYfj2J6A
            JEyeWX3bcnVBK8TAASf3jvRCLChnVa2qAyLVdCPhZ4NvJjOUtlreNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-25T21:03:51Z"
    mac: ENC[AES256_GCM,data:tgprmj4y26O4l+0ZeTITOWmjbozc/kL6BGlwZJV2F0slHkt6r9ITgkYZoYhhLn6LSMhvvJkYgiaJmrWiI13H0zYbzCXXCDwWqEs5+65+1+IzybXWTN2DTOYRGdQvqhgUfbhCJfpmmL0G3m5Pvjt8B+kkCmDz6nyylqr53zIAM0Q=,iv:xd19SK8ADdV52G6qu+CHfFF9DvEr8BlOqJVfB4KVxak=,tag:OESYvDaq/inT08+WngfvQg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
