ansible_become_pass: ENC[AES256_GCM,data:909S0Sgr9Yykh9gyfg==,iv:10pXuPsZ+aqmlwggs0KqYY8G561zN0rj+aakjqvJ4fw=,tag:9hQY2/lvyQX38qqtRD7K+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x7pwg44zy2dcydntr0n7rcdtekua2fgm3gsy63amu55lhktsnd7qw40grw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDYmVmaXRnOXlHK2NJS3hI
            ejhMbElQVVJlT0RBNDZyN3BTT2hycTl2aERBClJQVENnNFhzaWRCUUNqTjhsdktN
            Vi9hc2pZak16TXlFQkdTbDF2S1ZZc2sKLS0tIFNCaXZmVDY1OU91WEl4NFlUbkh3
            Z0hqQjNJL2p3dW1YNHBrRFRkM2lPMmsKu5fS9tEpElOtlZUkvVtdWEjJrjY/c6+O
            rWtxFOFJ6e0Cl9RWzH134aNjr5ka5XM2MbVhoSk0Jwb+QzPlkHLzeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-31T02:56:30Z"
    mac: ENC[AES256_GCM,data:n6lQLiKiJqyQCFzHD8fzvUCzi1nfJhIPFFenuqsvLfecNQ0qTHYJYxLCExM081S9T0rKfOSbW3mjQfZPf1d2amfZGWhnDhyEPvFiOJ7eZyLB5im+hvxi4EGgSttDklu/Wkg1Q87bBnLUQ6uCq/qNrTZuhoIDFdlVRVBkm0ja3tw=,iv:27E/q+08Bt0xtkz/W1sN0zE0Ng4l9AT69pdVpI85pfk=,tag:dmdckMODN5qQAhlNtuRpaQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
