apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: "nzbget"
  namespace: "media"
spec:
  releaseName: nzbget
  targetNamespace: media
  timeout: 2m
  interval: 2m0s
  chart:
    spec:
      chart: app-template
      version: "1.5.1"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: "ghcr.io/k8s-at-home/nzbget"
      tag: "latest"

    controller:
      replicas: 1

    env:
      TZ: "America/Chicago"

    podSecurityContext:
      fsGroup: 568

    persistence:
      config:
        enabled: true
        existingClaim: "nzbget-config"
      # media:
      #   enabled: true
      #   existingClaim: media

    service:
      main:
        enabled: true
        type: ClusterIP
        ports:
          http:
            port: 6789
            targetPort: 6789

    ingress:
      main:
        enabled: true
        ingressClassName: "internal"
        annotations:
          kubernetes.io/ingress.class: "internal"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          acme.cert-manager.io/http01-edit-in-place: "false"
          nignx.ingress.kubernetes.io/force-ssl-redirect: "true"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          external-dns.alpha.kubernetes.io/target: "${cloudflared_tunnel_uuid}.cfargotunnel.com"
        hosts:
          - host: "nzbget.${SECRET_DOMAIN}"
            paths:
              - path: "/"
        tls:
          - hosts:
              - "nzbget.${SECRET_DOMAIN}"
            secretName: "nzbget.${SECRET_DOMAIN}"
