apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nzbget-config
  namespace: media
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  storageClassName: freenas-nfs-csi
  accessModes:
    - ReadWriteOnce
