---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole-k8s
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: pihole
      version: 2.18.0
      sourceRef:
        kind: HelmRepository
        name: pihole-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: "pihole/pihole"
      tag: "2023.05.2"
      pullPolicy: IfNotPresent
    replicaCount: 1
    strategyType: RollingUpdate
    maxSurge: 1
    maxUnavailable: 1
    dualStack:
      enabled: false
    serviceDns:
      mixedService: true
      type: LoadBalancer
      port: 53
      externalTrafficPolicy: Cluster
      annotations:
        io.cilium/lb-ipam-ips: 192.168.100.11
    serviceWeb:
      http:
        enabled: true
        port: 80
      https:
        enabled: true
        port: 443
    virtualHost: "pihole.${SECRET_DOMAIN}"
    ingress:
      enabled: true
      ingressClassName: internal
      hosts:
        - "pihole.${DOMAIN}"
      tls:
        - hosts:
            - "pihole.${SECRET_DOMAIN}"
    persistentVolumeClaim:
      enabled: true
      existingClaim: pihole-data
      accessModes:
        - ReadWriteMany
      size: "2Gi"
    extraEnvVars:
      TZ: "Europe/Chicago"
      WEBPASSWORD: ${PIHOLE_PASSWORD}
    DNS1: "1.1.1.1"
    DNS2: "1.0.0.2"
    adlists:
      # DEFAULT LISTS
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      - https://mirror1.malwaredomains.com/files/justdomains
      - https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
      - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
      # SUSPICIOUS
      - https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt
      - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts
      - https://v.firebog.net/hosts/static/w3kbl.txt
      - https://raw.githubusercontent.com/matomo-org/referrer-spam-blacklist/master/spammers.txt
      - https://someonewhocares.org/hosts/zero/hosts
      - https://raw.githubusercontent.com/VeleSila/yhosts/master/hosts
      - https://winhelp2002.mvps.org/hosts.txt
      - https://v.firebog.net/hosts/neohostsbasic.txt
      - https://raw.githubusercontent.com/RooneyMcNibNug/pihole-stuff/master/SNAFU.txt
      - https://paulgb.github.io/BarbBlock/blacklists/hosts-file.txt
      # Advertizing
      - https://adaway.org/hosts.txt
      - https://v.firebog.net/hosts/AdguardDNS.txt
      - https://v.firebog.net/hosts/Admiral.txt
      - https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
      - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
      - https://v.firebog.net/hosts/Easylist.txt
      - https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
      - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts
      - https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts
      - https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts
      # Tracking and Telemetry
      - https://v.firebog.net/hosts/Easyprivacy.txt
      - https://v.firebog.net/hosts/Prigent-Ads.txt
      - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts
      - https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
      - https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt
      - https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt
      - https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/android-tracking.txt
      - https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV.txt
      - https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/AmazonFireTV.txt
      - https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt
      # Malicious
      - https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt
      - https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt
      - https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt
      - https://v.firebog.net/hosts/Prigent-Crypto.txt
      - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts
      - https://bitbucket.org/ethanr/dns-blacklists/raw/8575c9f96e5b4a1308f2f12394abd86d0927a4a0/bad_lists/Mandiant_APT1_Report_Appendix_D.txt
      - https://phishing.army/download/phishing_army_blocklist_extended.txt
      - https://malware-filter.gitlab.io/malware-filter/phishing-filter-hosts.txt
      - https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt
      - https://v.firebog.net/hosts/RPiList-Malware.txt
      - https://v.firebog.net/hosts/RPiList-Phishing.txt
      - https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt
      - https://raw.githubusercontent.com/AssoEchap/stalkerware-indicators/master/generated/hosts
      - https://urlhaus.abuse.ch/downloads/hostfile/
      - https://v.firebog.net/hosts/Prigent-Malware.txt
      # Other Lists
      - https://zerodot1.gitlab.io/CoinBlockerLists/hosts_browser
      - https://raw.githubusercontent.com/chadmayfield/my-pihole-blocklists/master/lists/pi_blocklist_porn_top1m.list
      - https://v.firebog.net/hosts/Prigent-Adult.txt
      - https://raw.githubusercontent.com/anudeepND/blacklist/master/facebook.txt
    whitelist:
      - https://t.co
