apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:yM+nmE4f7JiwJ+Jlsd5tkSwDZCEBRunz,iv:UTzSc4RSZfBJvZKvALqFK0c3kneW3AP0piNgOYNes7Y=,tag:jbEFpPP6Bkv9TjCmFmJNFQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x7pwg44zy2dcydntr0n7rcdtekua2fgm3gsy63amu55lhktsnd7qw40grw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJdlM1d1ZjTkFheGVpV3No
            MkJlUzZ3YXJLUWVDdTB2VUlPdXlnN1ZSRUg4CnVXVFBJZ2RML2ZTQmVIY2RNeFdz
            ODZEYWZYRHpBQTFDNUxMUHdkUWxqamsKLS0tIHBJMG1mb0pGWllQcEhVWkY1RGxl
            aWR5T0VINHphUzdtaDg0TTY4a1RMcTAKqCUAKOvIjEHuyCuTDRNIYHujy/q/gFAL
            HG2OxHOt8DH9Mf9W32HW02RIToaABSYyVGfhxL2mxtW37kZDysEa1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-30T19:03:47Z"
    mac: ENC[AES256_GCM,data:YL52EopbjetEbWhelyQVYx6KftTm5AV+EkP9NRRaDDeARCTC0iYu8VLFG0spzMmn+zVQ2yfits9LZWwiIshBRELcoLQtlMhXk1El2F/GPTFFwXvcYieLNxve84gzpl4m5CFVy+qLg/FiULzhPFJpgrk8asfOeAQ6iU1DVggM1hg=,iv:9+G6JykyfhroCtxXi/+b6bUuqXfLsiVR+7DkYsdfz+o=,tag:6E2HH3a9CtwKJKveg98+1Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
