apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:HLWuBYZvvF4kVC4MF2PHSObMQO5zRGnr4RlAvD9ur6O2iMjzNagQYw==,iv:5GEvufS+1a8WQAh5tAxrB39kNejrMjBWmC5vh+ICGnI=,tag:08+tLH2mz/bXEGRkilML0A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x7pwg44zy2dcydntr0n7rcdtekua2fgm3gsy63amu55lhktsnd7qw40grw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsbmNiWmwwNkw0Kzd6S204
            aXowZThocmZ0aEErNFJNN3Y3d1VTL1NNRkRZCmRrajFqYVc5OW9GbWJJNW1yT2th
            aDBLalZ5eU50c1lBRkMvNjVRb2pyRU0KLS0tIERxTWYyUDA2RTFQK0hFZThRbzdG
            MmI3eGVsN3ZNWVNIeTYvbkVoc3N4N2cKH9SuGAaFE3AIcNMzZC/kCdHPQVu0YI7o
            0FFQ1UYLuA96NgS8jrEkS6j1A6LXwz8o9sAxnBZOw45vZ3XG1Gll4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-25T19:16:25Z"
    mac: ENC[AES256_GCM,data:QqUP8SklhRNSYhpgOyfooKXZ7W6Kkg4bQ5ClTN39iJRGxDPbhXsBw9d4I8IaXgHHjLKYz0gHNEi5abaL1SgbPsNMlEGUL/86tTvFn6yJY4DO3IiempJfrVWP6EbhaiZ1opZYsQAm6NxKd6IJ5vMsq8c5enkpP0fRU6BGtuXfSSU=,iv:a2Ff906y0Gg22W1K1GzdkLLcUhxuyyjAV5e7hHt5n3A=,tag:4j5wU2w6IP3UWqhCkSrGPQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
