apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:lumXVluf+3xpDgqYcCBhf9HeqGJV2pBlTfQkfGHrqiSbmf94YRQmqg==,iv:Ebf0yfrnuXKQSbfJZEgqEY5BzcXNUwO1vsPD2y5o/vQ=,tag:wgHB5lILTv+barUPzF5MdQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x7pwg44zy2dcydntr0n7rcdtekua2fgm3gsy63amu55lhktsnd7qw40grw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0WCs5dHRRbHI4WDlpWUdi
            dUpFN2d4a1lGajQ0SDYvOTJBVDRmZS83M1VZClZheXoveWpZSXFyMExycmJ3M3FO
            dUY0eDk0WFQ3OVRiaE5QaVBlNE1ZYUUKLS0tIHBuNkxxblFOeWdHUC9hUGJnbUt0
            V0Y0R3cwYlBDV2VHWUl4Q0hoaUVITVEKkwLkxWsaBBmQilrHpLX6ey8ZLvMoypRs
            /Ox0+PA+dKSR2vinX3UHxHBx8lL98lejS51kXJDzSS9+2nQxxQnByQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-25T17:47:21Z"
    mac: ENC[AES256_GCM,data:t4t6ER5s8Kux44Gz2jgPlCI0MvgNwyXPchzKyCRN/m2BaDzetf28oqSSyaOhTVC7wNHPkX6hBZPiV+ND6sYG3719rbVwYzp7E3zlGNE/Hm+uq1N9pfslC+GjzdxwsvS8kOo3ahfjcRHJz3yh6eVLZ/9f/UZ45hlCI40ZTu00MoY=,iv:cWuCNLdVQ/LfcgtVIGXMtkuRuqCYsp04AItjOwxBYD8=,tag:SozS7c7A4i+57z1GvjVJoA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
