apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:O2NW5yK9xOcch6giKElvyJCV62Htxst7GnGbLp5KhQ+NKwo6/m2yMA==,iv:VQXr1+c5xTnSCIFXgoxIc+5wCi0IiWqbwRzpPBszkJM=,tag:LTwglqk0Yl9Rimr4b7SP0g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x7pwg44zy2dcydntr0n7rcdtekua2fgm3gsy63amu55lhktsnd7qw40grw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2ZnF2SEdRWW9IcVBISUtx
            NnVsUzF5K2lYN3ErMFhhdmdoTjI5VG9qaERRCllDWnVQSlhuamg4cjJ2ME1yazFx
            cThVK3FQdlNoeDJtemtzOWJJbUxTMFkKLS0tIFZGVXhEYXZweDRCK2gyOTZoOE4w
            dWV5S1JubmgwNGljclB0blNDN1BMN1kKp8b1u/a40KqthKvUv9DE61+XX4T4TVha
            qKXe9pgsYcD26wggPg8NjbYmp8V/bJnzaif7YBNJjfmsDfv1/hxN8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-30T19:03:48Z"
    mac: ENC[AES256_GCM,data:mVgc22FXzxb3/ahyvwtipeNqBwLcpDI1rbRem0rjPOnI+wYLUFUWC208FgNsD6utuUbU/8gPnhcZwW/6r3Xt2QnSAoQ5PDim1qAdLFBJdoKx+hM9NWzSnNg6ERF7YBu72jEjR8hDGevAWbNlXczwEboh7vWwb2krnEsNWpUcNoM=,iv:U3N4YFM8+n7vdVNkaHgmq4D7uDLqmLvCPiHOFvqyIb0=,tag:Ppoatm0+GWiNy2PRE/oL1w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
