# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: zfs-nfs-secret
    namespace: storage
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:bkxnJJY0wSWU4NOqV/sunpOcCaBvGbjJsxt26xIqx4hK2nYQNhGVaNjDWHlUpD0qFJjhN+KBCZVRElSGyAxV7JZTmyxp5l2ncsON3UJ+kW6cd2QoCP9a7ntx6+TzFr3HGknPL1clP7ha9Eygzq2JvYvLmUfXPwvevVL9HvCFNzt/MZVLdlWIdD5Bj8oOuua5zjdxcfH4YK6U29EppSgW8SchnnlOiY6FjBg0Ff4UimXnqumYn2jWwswcRB75ol8p+o/ctkE4QDBfGSFkSFK50ZycUD8xTeN15vPl0R91v+1Zej7IG2qPUBvhnvbXuxbmMV7hjIQu/Vhmcj1KgAseC7Ta+o+H+fV6NrbFo/lDsT9w24K/US5UuvjFzeGRcWT8yH7qURrelSMdDUqVQ6kqwRa9AIXJY1CencJPoo6Yfqax9IAch2lUAN0F6MNimKxQSA71L44yWHuJeqifAbMdi/vSnJroY59aQhGkPjnb4B6fY6ZZfcKNABZSluIEmS0dHTQq+auN8ga/1hl4PybzNd4jaDUZ4SLc0oFkn0Ok2sALwv/R3qXZOlRtZdim1C/DFBYi90PlQgc6Pmf90rNaT28tcsPyA1+kGdHt4WrRplrdJPf5Z+3YWnXDJONl98F5t6Xjy08N5dHQ7LDgEen2aVN3mb6NYfpIBTbft0rMvnax+oXne9c4UesM0z3IaIcKSlIVnijYcVF1G6yFCiISKy26xVPAGrQMQ9CvBVXl/Ntgbip4P8EZg2b+asfg0Pjkp47lkIIgZbpYaej3evMfmxrmLtOjiBHzavYZNSbW4wehudb1+sRLmmi+zsr43yi/rCWvHDGjIkDyDx/Hxu+eJLavm8BqOAEAEw==,iv:Rk2Nknr6/qbf5J50I0Iymcd797rAonhFi5WxMWxROV0=,tag:9s8Wgfn6LI1OdLB9S7zh7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x7pwg44zy2dcydntr0n7rcdtekua2fgm3gsy63amu55lhktsnd7qw40grw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYQm9rZk1GT3BIak5nbnhw
            dCtxTkxJWFNMN0gyelRBRUIxVms5K2tuS0JJCmcvRWN0aVZuRmtPSDdKaWJ3U0F5
            bzYrdktvYVJVMjl3OGFLNVBySDJiZm8KLS0tIEVuU3FaR0EwRzYrUm40OG9ieGhl
            NDl1bGxFWDZuZXR5WTBiWFNIWmoyWXcKADqJMezgHeflQnXNFNbw6yVdCESzN9Tg
            Jv1X5sgiG16SaOFDA3fmvUoXY3ecGaTlb7yACD76WJsYcQ53AwjXpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-11T13:39:20Z"
    mac: ENC[AES256_GCM,data:EfAiw52RxscU5uupBc6gaiJBrfUpz4I1uUM55BEa43eHWf/FY69xguFATnohsJXFGTbeHf991NfUSliIs9YN5jMpMTKl81fw4no+JSB6oZNmnwjYcYh1L1xCNZ8dvuBg/gK7FqZ5HJKNjaTZ+zt7L6emvnzu1RUe9X9n3/08Obw=,iv:i1MhY+NNOTuLLc1rEZkNor6lWzMmnlYscbL/HEBYbKM=,tag:lMi/SDFuzcklBdKWp8BVTQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
