# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: zfs-nfs-secret
    namespace: storage
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:z0FRyc4miyxnpA/w5gfGEXddEKMlCgKg+0Q40mmubT9IU+C8CGQcTFQ96aZQZ9vkUeVI6QGiFXD8uRItYvz46akF0lCOB4jmXrSYhkwCv/KKWGa87UCJnfdF2a/8Dhc7jLUfDt7QWkBxFjnN3TR/EvRzxBd99RPDIYGOEBgR3yPOtFfknUDJZWrBKEAqW8vMODHpJfaeYfKdPF/QmwX7x5rs7pE162A21XCs8HvWTVVNtlL/DeSFN9wxJLvxNlHujAOKgqolpgqzY9Wf9cToHrbafaSCuf5exexa0fwEqb+dNXWyxg7eohSII++zUCo9d8lfAfbDUDpguUxOhzzCaqE71TIwBP5+z4Ij2rHNKEUoRIq+KnY4zg8LoHDu+Ph71YyKal2/nME03AVmBXBxLGwlDC6RfhLQlCsANGu2VeP9Vu1nJVqHcaTJmtMQIFiUMylXRrtmauFUOdjCCrez5t7NcEYjHbcDZFs905HZiAjKF96/zuZ8pzvoXkQKIkanT710q4k2fp2KA+ERApSt/cO1QR0F3UF50Ga6xpS4+sd5GyhQ/SrF0j3YEaLT2f65JwkJ++aVucJV0ZzbPNATzxLJ5hQ5syPtAVjFSAXAn9vgajZw0icN/tSCIiX1c+QEv8NPx7g+arDXFZKg6Q0ooFxT8hkYzTBIct/7r7RpseNMArgaJAIS5V866MGd7Ak6/8XW6T+OOIL60JwF0BRUq5p/9LuQnaNhKeEHhm6+7zqilYjDJQvUeLwbdWFdW3Uo7IuMkOh4mxs1lGJ8dYRSQGamBKzwsLbrsMiSxAVd8F6Ej5tJz7UFhs21//aBS6FCZaP3rMBVmbiiloNK9S1tr2z+ndCwuiTO89FdyKcWhq7wADu6D5Jw/ydCIZNbk46VtVeTZGHOSOthV1PfZyu7/LKm28C44zRqN6sMQBds/3K61Z/ogVIvzDJSIA4VIAkt16b6mfHmiloByVck3TkwgS+9YbrZryJ7t7mYh/lRcoihzKpQS0FVC83gZ+PhIeDpnFHOWZxOG0fa2V7qIAf/m0SupMxv05po1v496mc5Fu6bjQSCDrl75N3VVAutZX1z/SRC+nV6UX68ry/7SzukvO/g4Ih4OOSfNzntKSN5k88=,iv:No3cG11Kto8RNdMv+PY/hmxw30TCVxcG9TDHx3XFgHw=,tag:Yh0YKqxuWOH+SVowRZanwA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x7pwg44zy2dcydntr0n7rcdtekua2fgm3gsy63amu55lhktsnd7qw40grw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuU2lOMVlKMG8rbDZ3eEpq
            ZVF1c3FsdlVtVE5WRTEyWVNGMGljN2J0RUZzCmFHbVVVODJiaEZ3YlZWQkJPeW1j
            bmo4M0pLR0k3RDNnTWF4NDRFbkZZU1EKLS0tIDF6WEFvcFc2V3kvcmRMV1JCa25z
            UE5odGJhand3d0JxV2lSbjNyNTVDZlEKmAyhb9f93sKH3XyKA086FhJ2/yJm4EsG
            Ky4D+axw72wzyR1dd+USAXDVglW8y4v8/t2Mn4oFHz7c/2bDsaPtFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-08T17:18:26Z"
    mac: ENC[AES256_GCM,data:pk3orANLh9LdkQKv13Zgt17mKeH8ePp3xeJKhtK5YLRxvkfkySvmzRvQUzEaJYVcb1CKwdSu9p7VibJ1+FTNfstK4iY21EdCAsbekzj3JLITlrkFxD1rWaMG5grjWXQTM905qHpSP4RatdgoqTauUYFns599uk5p1lF5JrkpPn4=,iv:5z9f6yOVccitDHdiWo0CWUCzWwCGUz2xyH5A6VazViI=,tag:3grnyTnKyI5W3KP6tZPVFQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
