# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: zfs-nfs-secret
    namespace: storage
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:gCjXhaKtAEdqWQLlr6epzY7YVDV1CTOOM5NzeVNYEmqrpwenMwNKrywJllDWmzPqXlyxnPxd+aYpuk24c0tywIyybW8IeFMmYukVZtX2BfUiPXP4apsoCbd3mE2u0XSrS7A6d2quRTDSDK1qz0FRYqAyUEu6QVkGqCkLhZg1gp0U/hFtye97P0LFu9EYK2DOZSOm6DX4QNY3GOrKn434Bnwnr4PRXtft6SJdnJTjY6MJoqhDhfuNavAa11QEuEATMWdAh5bCDx4hsLR8vKM5HDFZQlcbmqQA+gKi25uc99zNRbW3OPhQaS3Z86YUkXxddSpRIaEHhInXUO3yVjh5eSRhIGBNRIb0iUGKYihs3Rip6P1ivyp9lzvSMI4c/JPWzkxM7mwC5V4ES9NbgHqD1x/0uYnRJpFtmDLwJeY5nz2yKdWMO8W/1VV1jnQSkCCGsYzkUspbuHnwLZtU7egHLhyLg88eOGwuNKtyaI8k0bUVfqFuJObaSlbHI/Zvc1QuyHEPPqbopID8k4GXvg+tfgUelnYr+1Gq73oLJ8aa05noQ4+I2GFWxcGzf5W3a7jEpYCDzyY4TShi1qq4hWavPDtVUKZCH+PmEPwp4VLSSx6BnIDil23rg0N64m8l4nHdp5zdffggSZ3hCy77wEhrZVB/ZOwPtGuswhtSyTFO0K0nR95GVEVsIc8DNJzj5eJAEPS4KcNbXd1uCoGYOnVNzoVmR6w4+LBsq7EkqPi9B0gar+6WFDsC5vLhZBnv/1+zxacaOhP9SCxmbUqumgKrdU1FbGyGGPvfPDeIAfE+44g7RKTlPABGvRF3eD8Aax6VzSRhpZW5x9c/sEAvQWnlMXl67UfFwPP7DwWGGqISzHJ5F9Ui0ZgiFZDYJmTF9LxZFjeaY+pK3S3zRxjLEXSFLrNivDSxNOz7jwhpNdSIAnJjbHy5a5CfbtmMGYtTMaewXB0G26eQj631JxrZ3AWvI+EmVf5eOiTWbWLdw1Hcp88c1p/87+R7+rOd9tTsJZ9dtbWgerotpcjFFlZ7pB+kI1SbWYQzFhgmoH4HgZnlVVVhH1TjC20a/Rq99xDh61x/krsZlmZsGuU9DTCNTvV32q/dnBPPuxIzQIYIMV1CeUQ=,iv:PtHMQtabqCXQ1YF9ej5vvdlO7b0xT8LEdnYom6T1Qy4=,tag:dSCQvvKSlqzwlcd88cKdHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x7pwg44zy2dcydntr0n7rcdtekua2fgm3gsy63amu55lhktsnd7qw40grw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQZHJoajFhd1NVT2R5c3pQ
            bDFrR0Q4UURUTFIrMzU0M0RlNHdCSUtzSFRnCkxJWGVVK01hcFVya0hBQXJNZW00
            UGhQVVJ6MG8vaExsYmdGLzRsNm1VV2sKLS0tIDVZeE9wM055ckFXNWh3UmJuaXNj
            U2VVbGYrQ1ZOdEg5NUhwcjF0TG80SG8KnhU2/177lKZFQVv+5mmQuW0rN06VK3c+
            34A23ZFbZbvNNswIUBHa5D1s71yv9nxWEbHFvK/WlZ8nmJar+6f7GA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-08T16:18:47Z"
    mac: ENC[AES256_GCM,data:2t8y6lCU+yOsrW2piJ30Br9E0zgVKtzXZ6OLr5rif2oFLjdks+qX++vVemExEkezHnyQI8NVZRIxI304Lx20WFbbh0oVJwfHzcrKVGgdILHY0r2cBxWDmroEVTWZRLuLnV55mQoKtvSpMnytplahYhXRT2ykIIv8h2VVW99P1Gw=,iv:6bsRotRHnLy6ua4g+wHj0D2B9cwbneFOEmfZSmqvY2Y=,tag:d+iCaChzABCp59qsC2SpKQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
