apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:8vehkiQIjqKWiyx36RbhO/x2M/C7zvjq/MHopiFgzbwfEa6DxsD7BgSiUIKotPsfGDcm7T5B4O0R2Koz,iv:acEQL01OoHWxAi3Ad7FrcdVwXawJLYVP6wqV2SUvytA=,tag:e8y48dGZIvkWNMmU2CF7pQ==,type:str]
    username: ENC[AES256_GCM,data:a7SrQzo=,iv:r1D06H7lb/dpMi13ZSMMHhRO0K49GgTfx7elLqsG9c4=,tag:C3XYTWb7cmMd2cU0MUqs7w==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x7pwg44zy2dcydntr0n7rcdtekua2fgm3gsy63amu55lhktsnd7qw40grw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2aVZ4em1vNmlrejVFbXht
            ZkVLSVo1UjRGQ0hQSHVzcFcyY3hNcDE2cEg4ClpKRkZ4bHZhb1hTYTNKdGlSRWFl
            RWFQTTd6cmQzekN0T1VWVjVaamQyWGcKLS0tIGk1Rys1dXNlcDZjbnlFWnhwNzZh
            S2lnNUhFclNIbjNFWEZlb0gydWxEMWsK4pIKl49PzysnViN7vJmvdQDW4RU0ENdl
            spkCGix+LQWI0jG3kKPUp0jz/tFCqWecRhE5lMOU7PM1Gh3HS8zMKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-25T17:47:56Z"
    mac: ENC[AES256_GCM,data:Uj4Pihidmlco3v/Y2PGbRNmSzqiB5LFSoB4YlByzeJG8VDp/Ukajpk7ejwCG0qu+XhfH39EJf/b43f95MfGvDfVKg6wPiVB0bEdKnjOdsU5IZ7uQSljoT/B1C6Mutvc2PojrIjyKDQ75F4DgA4K0KkIeB2NNbE+WQdeypdam77A=,iv:M4qjdr0mGnD/KdwOsrHQvO5+LmbqJ2bFhO1yqhfBb3M=,tag:+ZN3uQnt2WTLt2qPrfxhRQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
