apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:/+MyeAiGBpkOwagKsqOngnE=,iv:xlnWUwBRyLylOwBAp9+IvqANUf+RJYpQb5Eelj4mqpQ=,tag:loq0YVkUZsYgWilCKR2oVA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:uYXOQ4EENa50O63FMh3/7yyM1fohOQeCPhgZlaG5zAAtXAKh,iv:vyHTQvyy0HtoLvObXLeXnwY/L82WXvGXBvxXhXXXgbk=,tag:cG+8U1GO5bT50U1S7MrPLw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:QT/ToDPYb5nEsOBdSA==,iv:qHWVlIwzOnTElW+o2gVjXag4c719UyBBD6ZzkvOY72M=,tag:x+fGz8XJdK26eUDk34JuVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x7pwg44zy2dcydntr0n7rcdtekua2fgm3gsy63amu55lhktsnd7qw40grw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKRU5kaTZ3R1duQUVwdGhR
            RFhLVE0wd2l3bjFhSEF1U3FkTjhzUmNjaGdBCm1TbFdUSTRYYzlheURtLzFZWk5W
            aVRQQ3F5V0JRaGdkTnltQmVlcVFmNDAKLS0tIGFEU25WTVUzUUNsSjgvUGNadldQ
            ZmlKNGhSZTQrUHVQK2pyb25XZWJaRXcKG87ug2Y8prfOZGgZ9/FWTxvTUU8jn49c
            dc5U10KPM65dBsF8keZSQ36GyG348wJwZsm7SmTGISmaHnIqklLa6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-24T01:23:09Z"
    mac: ENC[AES256_GCM,data:eJDafZl2FYni6N40/8lm/gld6ZmKZVyWrAX0FAICjDbY0fk1GAxJL8dhMSEZjS6jF8jobasKTu9wN3khdjIsh2HPl/DqeIRtNNhIQRd3k+09A1Vz3WKPQvOCIbIEw2W3Oai/zkHJXr7ANQ+Z2yztHwbkB/+EqeM1+AMG0Bhx8H0=,iv:L9aUXQWKwnGICT7hRPZHKE14c/YTayaguoi3TUbU9Aw=,tag:hsvy9BNa+jxiXNXQAJB1Ng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
