apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:j53wGA+MqatuHbId,iv:NSEum2WLmbqk9cibHpy3DwIaWhQjnu2DRMV5J3/MXag=,tag:Y3gcBn3D9bIdcn7iX9Ystw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x7pwg44zy2dcydntr0n7rcdtekua2fgm3gsy63amu55lhktsnd7qw40grw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdVIyekVEMkNHTklCbWJZ
            cjcvaWVSOFhGREt1aStKaGJ6Q0NNTWVUbUI4CmVmS1RGL1kyalBiU083L1kyL2ln
            MCtmUDJheHlXQ2cxT2NOcTN6Yy9HMDgKLS0tIG5OK1hJV3JrS2g1L2xKRDJrbzJs
            SU91emt6d0NlRlBOY2VPUEt1QWM1MlEK49MJBIJ/0wWtVwdSZSpmkrrBWYD2mWN6
            8CrA8r5b0fGjvjw+AYv967d1rQjCedRoOYUTAQ8MYPoJYwccpAuCkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-31T02:58:40Z"
    mac: ENC[AES256_GCM,data:Rz956bW8l8ikEwjQFtEOtkNvj1Kq2EjfHmsqG/C5VDpVsv9/jmDN8CXy3rkC7fNNyTlhMcbhvxQsvOskHvLoRxCAP1iRKtts0+8av2+ObhPfpibHHpOICaAnmuHkHDC8y2pS8sjHkI0knJRBUFhbWe5kmEFkKIjia46B38LxQyU=,iv:C4Tp19y4HAp6V6VkS4Xot89TnGrETiSFvoRHWqMZAtI=,tag:GvJ/D1mRuB2798TTQ7wi5Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
