---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: "plexinc/pms-docker"
      tag: "latest"
    env:
      TZ: "America/Chicago"
      ADVERTISE_IP: "https://plex.${SECRET_DOMAIN}/,http://192.168.100.12:32400"
      PLEX_CLAIM: "${PLEX_CLAIM}"
      PLEX_PREFERENCE_1: "LanNetworksBandwidth=192.168.100.0/24"
      PLEX_PREFERENCE_2: "TranscoderQuality=0"
      PLEX_PREFERENCE_3: "TranscoderH264BackgroundPreset=fast"
      PLEX_UID: 1000
      PLEX_GID: 1000
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: "OnRootMismatch"
    ingress:
      main:
        enabled: true
        ingressClassName: "external"
        annotations:
          hajimari.io/icon: mdi:plex
        hosts:
          - host: "plex.${SECRET_DOMAIN}"
            paths:
              - path: "/"
                pathType: Prefix

    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        annotations:
          io.cilium/lb-ipam-ips: "192.168.100.12"
        # primary: true
        ports:
          http:
            port: #port 32400
            protocol: TCP
          dlna-tcp:
            port: 32469
            protocol: TCP
            enabled: true
          dlna-udp:
            port: 1900
            protocol: UDP
            enabled: true
          plex-companion:
            port: 3005
            protocol: TCP
            enabled: true
          discovery-udp:
            port: 5353
            protocol: UDP
            enabled: true
          plex-roku:
            port: 8324
            protocol: TCP
            enabled: true
          gdm-32410:
            port: 32410
            protocol: UDP
            enabled: true
          gdm-32412:
            port: 32412
            protocol: UDP
            enabled: true
          gdm-32413:
            port: 32413
            protocol: UDP
            enabled: true
          gdm-32414:
            port: 32414
            protocol: UDP
            enabled: true
    persistence:
      config:
        enabled: true
        storageClass: freenas-nfs-csi
        type: pvc
        accessMode: ReadWriteOnce
        size: 50Gi
      transcode:
        enabled: true
        type: emptyDir
