apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:oAAcKcim5PBdN/j6wRguVVwBk0WtEJRDu1rYp1eBfOD6Q72m,iv:pjMw2hPbN7ABbCuevolBkYDMSEVhX8MhO1hNdKA06lo=,tag:fUN94o63D8B6JO9dFJFrJg==,type:str]
    credentials.json: ENC[AES256_GCM,data:+T/065AFy4uooEFFCHQMtVcuML46fHL3CCo/Fbz1eteJiBiwHhHPlqx5HekEyQTx2KCqIv8oN94ft0eJkzHQaeGS5oKGJ91vXR8i6YW++vuaEBbPJZ2FtDYlGBZqCedB5Q4zk4tFYybUepS3sP7+nMW+8R82Y5q0RsrNO/OsMbCxDrhveqFAAuFy/PyROErnfAIFgGI8PnVbzD/xP6CoiSZiQtnyj9Ha5ldCMaqmSg==,iv:GQ79j2fAtcZodw42KJQiRbmh3h4+lxBWiLlmByTPw1Y=,tag:JMEWUmEEo/uZpHjx+LzOjg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x7pwg44zy2dcydntr0n7rcdtekua2fgm3gsy63amu55lhktsnd7qw40grw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuTHhuS3VES1lUZEp2SFpk
            S0YzcFBWNVFhdkh6Q2JUT2I4QUxOU1FhbDFvCnMwWTlJekFNR1VtWElzcFN3UXRI
            TVlpM1BQOWg4a1lUUUdkNDlPMkpsNmcKLS0tIEdhcnlFZ09veFFjNXFWenhjNVlJ
            VmFJQ2lMcEtuMXBBMnp2UEc1dVFMazAKInN31C7B4pnE0mn5yi/qqBjHetQEDoDb
            o0lqIkdVKfjNsh8FbuRN+iebeKT4lggkE5rH5sEIh88efOXYYc+n1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-25T21:06:20Z"
    mac: ENC[AES256_GCM,data:O0thrbbqk32Yz3jAeb9XphlncrJXUTGJA5jsrCMEWq1N4Zxumt0ojw9hb252Jp/1ftNyTU06XERU1xouhjEj4BpZMvyD3Vb4jVq6wFXqE1q4mL7dJ/gIkrey6xXw0PeReZMZ8b2Ep8He63L+0OfYLHnZzsoq9cqz+lWsepYVtZM=,iv:XhGsFd0t0H5Nbw+Qfo0kG0hmKsfOWesvskIAT3u3OV8=,tag:oH9Tu7mhS+eAKBrXyEALtw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
