# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: nfs-provisioner-vars
    namespace: storage
stringData:
    CONFIG_NFS_SERVER_IP_ADDRESS: ENC[AES256_GCM,data:zAKVvI0A3gVHUNC3sCGi,iv:sMiQQK4GL5J2PcU+f52pjB/szTYV7pwZF0mOZk1upbg=,tag:s0oa/LafCmH7iE1E3ynggQ==,type:str]
    CONFIG_NFS_SERVER_PATH: ENC[AES256_GCM,data:uHJKSR6QhHC22rb2QKo=,iv:UdSSW1qJJ10sqPi8ff7kOx6Sd4AACARMc9xoJPR8c3Y=,tag:6NAMTa91VakrwVutKQqJ9Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x7pwg44zy2dcydntr0n7rcdtekua2fgm3gsy63amu55lhktsnd7qw40grw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrcE4vaGNITStBdTgxN0tS
            VThqTWJ5RlB0MmU3VmlIQkhtNXQxQzBZbjNZCjR2MXhDdmI5SVY5NVRQNjN5V0tD
            Q3BPR3ZHUkhuVXRJQi9aTEhhNE1ESWMKLS0tIGlCVjhQUmVwbGdOMzdjVEU3bGZG
            YTNhOWhQN2x6RisyY1Q1Znl4b0t5QmcKEoStb7Tt3YgX9COsEzXZ9NYzElI/2FyS
            K5xp34SsTexBOt2n3/cle2jJPBM9GvzNx4ccdK1vZ0fp+61qv4DB0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-13T22:41:16Z"
    mac: ENC[AES256_GCM,data:X+ft9DkF6WpDcCqIM9Kxkwb+ge9ElPy8J3ePPA/TabyLJnnPnBtoD48Au4D7whEFO4uyuf6hsbuXPEVKFvC83u3keSOKzskPo+MSmglH/JnvhQi0x2S5fa2TzMgTluP5WFrAYEhdMiMsCRB077FBRPrpeQbe7NK+N9tm3hM/0VQ=,iv:hIU4S/lHocaL1Y8dkK0AilPEXIqfebQL8HQdG24+MKE=,tag:519aFYKB2KmvoEUb8ddYhQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
